# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-31 13:29
from __future__ import unicode_literals

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160830_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('student_class', models.ForeignKey(on_delete=app.models.Class, to='app.Class')),
            ],
        ),
    ]
